# Çoklu Doğrusal Regresyon (Multiple Linear Regression)

* Çoklu Doğrusal Regresyonda tahmin yaparken sonucu etkileyen birden fazla etken vardır. "Çoklu" kavramı da buradan gelir.

* Gerçek hayatta bir evin fiyatını sadece metrekaresi belirlemez. Oda sayısı, bulunduğu kat, şehir merkezine uzaklığı gibi birçok faktör vardır.

## ÖRNEK
Bir öğrencinin sınav notunu tahmin etmek istediğimizi düşünelim. Bakacağımız etkenler şunlar olabilir
* Kaç saat ders çalıştığı, 
* Önceki sınav notlarının ortalaması
* Gece kaç saat uyuduğu
Bu yöntemde her bir etkenin sonuca ne kadar etki edeceği (ağırlığı) hesaplanır. Mesela ders çalışmak notu çok yükseltirken, uykusuz kalmak biraz düşürebilir. Algoritma bu ağırlıkları belirleyerek bize bir formül sunar.

$$Y = \beta_0 + \beta_1X_1 + \beta_2X_2 + \beta_3X_3 + ... + \epsilon$$

# KUKLA DEĞİŞKEN (DUMMY VARIABLE)

* Dummy variable (Kukla Değişken), modelin içine dahil edilemeyen metinsel(kategorik) verileri, modelin anlayabileceği sayısal (0 ve 1) formatına dönüştürme yöntemidir.
* Bir modele girdi olarak kadın veya erkek yazamazsınız veya şehirleri matematiksel işlemlerde kullanamazsınız.

## NASIL ÇALIŞIR?
* Dummy variable yöntemi, her bir kategori çin yeni bir sütun oluşturur ve o satır ile ilgili kategoriye aitse 1, değilse 0 verir.

## ÖRNEK

AraçNo	Renk
1	Kırmızı
2	Mavi
3	Kırmızı

* Dummy variable dönüşümünden sonra
AraçNo	Renk_Kırmızı	Renk_Mavi
1	        1	            0
2	        0	            1
3	        1	            0

## KRİTİK KURAL: DUMMY VARIABLE TRAP (KUKLA DEĞİŞKEN TUZAĞI)
* Dikkat edilmesi gereken en önemli şey, oluşturulan yeni sütunlardan birini dışarıda bırakmaktır.
* Eğer 2 kategori varsa (kadın/erkek), sadece biri için sütun oluşturmak yeterlidir. Çünkü bir kişi "Erkek:0" iste zaten otomatik olarak "Kadın:1" olduğu anlaşılır.
* Tüm sütunları modele eklersek, değişkenler arasında mükemmel bir bağımlılık oluşur ve bu da modelin matematiğini bozar.

# P-VALUE (OLASILIK DEĞERİ)
* Yapılan tahminin ne kadar `anlamlı` olduğunu gösteren bir ölçüttür.
* En basit tabirliyle: 'Bu sonuç tamamen şans eseri mi oldu, yoksa gerçekten bir sebebi mi var ?'

# ÖRNEK
Kahve içmek odaklanmayı arttırır mı ?
- İki ihtimal var:
1. Sıfır Hipotezi(Null hypothesis): Kahve ile odaklanma arasında hiçbir bağ yok. Bu sonuç tamamen tesadüf.
2. Alternatif Hipotezi: Kahve gerçekten odaklanmayı arttırıyor.

P-Value, sıfır hipotezinin doğru olma ihtimalidir.
**P-Value çok düşükse:** Bu sonucun tesadüf olma ihtimali sadece %1. Yani tesadüf olamaz, demek ki kahve gerçekten etkili.
**P-Value yüksekse:** Bu sonucun tesadüf olma ihtimali %50 demektir. Yani emen olamayız şans eseri olabilir.

## KRİTİK EŞİK
* Makine öğrenmesinde kabul görmüş sınır 0.05'tir (%5)
* P <0.05 ise, sonuç istatistiksel olarak anlamlıdır, tesadüf değildir.
* P> 0.05 ise, sonuç anlamlı değildir, tesadüf olabilir.


# ÖRNEK 2
Diyelim ki bir evin fiyatını tahmin ediyoruz. Regresyon modelini kurduğunda her bir değişken için ayrı bir P-Value hesaplanır.
* Metrekare (P-Value:0,001) --> Çok önemli bir değişken, modelde mutlaka kalmalı
* Binanın rengi (P-Value:0.850) --> Fiyat üzerinde hiçbir anlamlı etkisi yok.

## ÖZETLE
P-Value değeri ne kadar küçükse, o değişkene o kadar çok güveniriz.

# MAKİNE ÖĞRENMESİNDE DEĞİŞKEN SEÇİMİ

`Beş farklı yaklaşım var`

1- Bütün Değişkenleri Dahil etmek (All-in)
* Bu yöntemde seçici davranmayız, tüm verileri modelin içine atarız
* Değişken sayısı çok azsa veya hepsinin çok önemli olduğu durumlarda kullanılır


2- Geriye Doğru Eleme (Backward Elimination)
``
* Bunu bir eleme turu gibi düşünelim:
    1- Önce tüm değişkenlerle başlarız.
    2- Her birinin P-Value değerine bakarız.
    3- En yüksek P-Value değerine sahip olanı modelden çıkarırız (Anlamsız olduğunu ifade eder)
    4- Kalanlarla tekrar model kurarız
    5- Ta ki tüm değişkenlerin P-Value değeri belirlediğimiz sınırın (genelde 0.05) altına inene kadar devam ederiz.
``

3- İleriye Seçim (Forward Selection)
* Backward yönteminin tam tersidir:
    1- Sıfır değişkenle başlarız (boş küme)
    2- Değişkenleri tek tek deneriz. P-Value değeri en düşük (en anlamlı) olanı sisteme ekleriz
    3- Yeni değişkenler ekledikçe model artık iyileşmeyene kadar devam ederiz

4- İki Yönlü Eleme (Bidirectional Elimination)
* Hem ileri hem geri yöntemi aynı anda kullanır
    1- Bir değişkeni içeri alırız (İleri seçim gibi)
    2- Hemen ardından, içerideki değişkenlerden hala anlamlı mı diye kontrol ederiz, anlamsızlaşanı atarız (geriye eleme gibi)
    
5- Skor Karşılaştırması (All Possible Models / Score Comparison)
* Eldeki değişkenlerin her türlü kombinasyonu için ayrı ayrı modeller kurarız
* Modellerin başarısını ölçeriz, başarı kriterini biz belirleriz.
* En yüksek skoru veren kombinasyonu seçeriz
* En zahmetli yoldur.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

veri=pd.read_csv('data.csv')
veri.head()

FileNotFoundError: [Errno 2] No such file or directory: 'veri.csv'

In [ ]:
c = veri.iloc[:,-1:].values
from sklearn import preprocessing
le =preprocessing.LabelEncoder()
#LabelEncoder harfleri sayıya çeviren bir araçtır.
c[:,-1] =le.fit_transform(veri.iloc[:,-1])


ohe = preprocessing.OneHotEncoder()
#OneHotEncoder, sayıları 0 ve 1li sütunlara ayıran bir araç oluştur demek.
c = ohe.fit_transform(c).toarray()
print(c)




[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [ ]:
ulke = veri.iloc[:,0:1].values
ulke
#Veriden ulke sütununu çektik

array([['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr']], dtype=object)

In [ ]:
le = preprocessing.LabelEncoder()
ulke[:,0] = le.fit_transform(veri.iloc[:,0])
ulke
# çektiğimiz ulke sütunundaki değerleri sayısallaştırdık

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=object)

In [ ]:
ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()
# sayıları sütunlara yerleştirdik
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [ ]:
sonuc = pd.DataFrame(data=ulke, index=range(22),columns=['fr','tr','us'])
sonuc

,fr,tr,us
0,0.0,1.0,0.0
1,0.0,1.0,0.0
2,0.0,1.0,0.0
3,0.0,1.0,0.0
4,0.0,1.0,0.0
5,0.0,1.0,0.0
6,0.0,1.0,0.0
7,0.0,1.0,0.0
8,0.0,1.0,0.0
9,0.0,0.0,1.0


In [ ]:
sonuc3 = pd.DataFrame(data=c[:,:1],index =range(22),columns=['cinsiyet'])
sonuc3

,cinsiyet
0,1.0
1,1.0
2,0.0
3,0.0
4,1.0
5,1.0
6,1.0
7,1.0
8,0.0
9,1.0


In [ ]:
yas_verileri = veri.iloc[:,1:4].values
sonuc2=pd.DataFrame(data=yas_verileri,index=range(22),columns=['boy','kilo','yas'])

In [ ]:
s = pd.concat([sonuc,sonuc2],axis=1)

In [ ]:
s2 = pd.concat([s,sonuc3],axis=1)
s2

,fr,tr,us,boy,kilo,yas,cinsiyet
0,0.0,1.0,0.0,130,30,10,1.0
1,0.0,1.0,0.0,125,36,11,1.0
2,0.0,1.0,0.0,135,34,10,0.0
3,0.0,1.0,0.0,133,30,9,0.0
4,0.0,1.0,0.0,129,38,12,1.0
5,0.0,1.0,0.0,180,90,30,1.0
6,0.0,1.0,0.0,190,80,25,1.0
7,0.0,1.0,0.0,175,90,35,1.0
8,0.0,1.0,0.0,177,60,22,0.0
9,0.0,0.0,1.0,185,105,33,1.0


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(s,sonuc3,test_size=0.33,random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)
#Örnek soru ve örnek cevapları makineye fit ettik(öğrettik)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [ ]:
y_pred = regressor.predict(x_test)
#Gerçek soruları verip cevapları istiyoruz
y_pred

array([[ 0.98720204],
       [-0.12036863],
       [ 0.05009703],
       [ 0.07137418],
       [ 0.72473935],
       [ 0.64615044],
       [-0.03567453],
       [ 0.32612171]])

In [ ]:
s2
boy = s2.iloc[:3,:4].values
boy = s2.iloc[:, 3:4].values

In [ ]:
sol = s2.iloc[:,:3]
sag = s2.iloc[:,4:]
veri = pd.concat([sol,sag],axis=1)
veri
#boysuz veri


,fr,tr,us,kilo,yas,cinsiyet
0,0.0,1.0,0.0,30,10,1.0
1,0.0,1.0,0.0,36,11,1.0
2,0.0,1.0,0.0,34,10,0.0
3,0.0,1.0,0.0,30,9,0.0
4,0.0,1.0,0.0,38,12,1.0
5,0.0,1.0,0.0,90,30,1.0
6,0.0,1.0,0.0,80,25,1.0
7,0.0,1.0,0.0,90,35,1.0
8,0.0,1.0,0.0,60,22,0.0
9,0.0,0.0,1.0,105,33,1.0


In [ ]:
x_train,x_test,y_train,y_test = train_test_split(veri,boy,test_size=0.33,random_state =0)

In [ ]:
r2=LinearRegression()
r2.fit(x_train,y_train)

y_pred=r2.predict(x_test)
y_pred

array([[182.26638686],
       [152.87161474],
       [162.79386375],
       [158.30668577],
       [130.82888952],
       [173.96138408],
       [150.12782663],
       [157.26898922]])

# BACKWARD ELIMINATION

In [ ]:
import statsmodels.api as sm

In [ ]:
X = np.append(arr=np.ones((22,1)).astype(int), values=veri, axis=1)
X

array([[  1.,   0.,   1.,   0.,  30.,  10.,   1.],
       [  1.,   0.,   1.,   0.,  36.,  11.,   1.],
       [  1.,   0.,   1.,   0.,  34.,  10.,   0.],
       [  1.,   0.,   1.,   0.,  30.,   9.,   0.],
       [  1.,   0.,   1.,   0.,  38.,  12.,   1.],
       [  1.,   0.,   1.,   0.,  90.,  30.,   1.],
       [  1.,   0.,   1.,   0.,  80.,  25.,   1.],
       [  1.,   0.,   1.,   0.,  90.,  35.,   1.],
       [  1.,   0.,   1.,   0.,  60.,  22.,   0.],
       [  1.,   0.,   0.,   1., 105.,  33.,   1.],
       [  1.,   0.,   0.,   1.,  55.,  27.,   0.],
       [  1.,   0.,   0.,   1.,  50.,  44.,   0.],
       [  1.,   0.,   0.,   1.,  58.,  39.,   0.],
       [  1.,   0.,   0.,   1.,  59.,  41.,   0.],
       [  1.,   0.,   0.,   1.,  62.,  55.,   0.],
       [  1.,   1.,   0.,   0.,  70.,  47.,   1.],
       [  1.,   1.,   0.,   0.,  90.,  23.,   1.],
       [  1.,   1.,   0.,   0.,  80.,  27.,   1.],
       [  1.,   1.,   0.,   0.,  88.,  28.,   1.],
       [  1.,   1.,   0.,   0.,

In [ ]:
X_l = veri.iloc[:,[0,1,2,3,4,5]].values
X_l=np.array(X_l,dtype=float)
#statsmodel float veri beklediği için float'a çeviriyoruz

model = sm.OLS(boy,X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Sun, 26 Apr 2026   Prob (F-statistic):           5.41e-07
Time:                        11:14:39   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           114.0688      8.145     14.005      0.0

In [ ]:
X_l = veri.iloc[:,[0,1,2,3,5]].values
X_l=np.array(X_l,dtype=float)
#statsmodel float veri beklediği için float'a çeviriyoruz

model = sm.OLS(boy,X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Sun, 26 Apr 2026   Prob (F-statistic):           9.32e-08
Time:                        11:16:17   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           115.6583      6.734     17.175      0.0